code --install-extension RobinMalfait.prettier-eslint-vscode
code --install-extension akamud.vscode-theme-onedark
code --install-extension apollographql.vscode-apollo
code --install-extension attilabuti.vscode-mjml
code --install-extension burkeholland.simple-timer
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cstuder.gitlab-ci-validator
code --install-extension davidmart.theme-jsfiddle-like-syntax-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension DSKWRK.vscode-generate-getter-setter
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fatihacet.gitlab-workflow
code --install-extension formulahendry.auto-close-tag
code --install-extension hitode909.zentabs
code --install-extension idleberg.emoji-code
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension jevakallio.vscode-hacker-typer
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mikestead.dotenv
code --install-extension mohsen1.react-javascript-to-typescript-transform-vscode
code --install-extension mpontus.tab-cycle
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension ngryman.codesandbox-theme
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension Prisma.vscode-graphql
code --install-extension rbbit.typescript-hero
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension sdras.night-owl
code --install-extension seunlanlege.action-buttons
code --install-extension shaharkazaz.git-merger
code --install-extension silvenon.mdx
code --install-extension stpn.vscode-graphql
code --install-extension t7yang.hyper-javascript-snippets
code --install-extension Tyriar.lorem-ipsum
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vstirbu.vscode-mermaid-preview
code --install-extension WakaTime.vscode-wakatime
code --install-extension WallabyJs.quokka-vscode
code --install-extension WallabyJs.wallaby-vscode
code --install-extension wix.glean
code --install-extension zhuangtongfa.Material-theme
